name = "StepFunctions"
uuid = "e7075c2b-82aa-4c73-be05-3661d86852bd"
authors = ["davidhien <david.hien@outlook.de> and contributors"]
version = "1.0.0-DEV.3"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
MakiePltExt = ["Makie"]
PlotsPltExt = ["RecipesBase"]

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
